= Spring MVC Test HtmlUnit
Rob Winch

This project's aim is to provide integration between https://docs.spring.io/spring/docs/3.2.x/spring-framework-reference/html/testing.html#spring-mvc-test-framework[Spring MVC Test Framework] and http://htmlunit.sourceforge.net/[HtmlUnit].
This simplifies performing end to end testing when using HTML based views.
Spring MVC Test HtmlUnit enables developers to:
m
* Easily test pages using tools (i.e. http://htmlunit.sourceforge.net/[HtmlUnit], https://www.seleniumhq.org[WebDriver], & http://www.gebish.org/manual/current/testing.html#spock_junit__testng[Geb]) that we already use for integration testing without starting an application server
* Support testing of JavaScript
* Optionally test using mock services to speed up testing.

NOTE: MockMvc will work with templating technologies that do not rely on a Servlet Container (i.e. Thymeleaf, Freemarker, Velocity, etc).
It does not work with JSPs since they rely on the Servlet Container.

== Why Spring MVC Test HtmlUnit?

The most obvious question that comes to mind is "Why do I need this?" The answer is best found by exploring a very basic https://github.com/spring-projects/spring-test-htmlunit/tree/master/mail-webapp[sample application].
Assume you have a Spring MVC web application that allows CRUD operations on a https://github.com/spring-projects/spring-test-htmlunit/blob/master/mail-webapp/src/main/java/sample/data/Message.java[Message] object.
The application also allows paging through all messages.
How would you go about testing it?

With Spring MVC Test, we can easily test if we are able to create a `Message`.

[source,java]
----
include::{samples-src-test-java}/sample/mockmvc/MockMvcCreateMessageTests.java[tags=create-message,indent=0]
----

What if we want to test our form view that allows us to create the message? For example, assume our form looks like the following snippet:

[source,xml]
----
<form id="messageForm" action="/messages/" method="post">
  <div class="pull-right"><a href="/messages/">Messages</a></div>

  <label for="summary">Summary</label>
  <input type="text" class="required" id="summary" name="summary" value="" />

  <label for="text">Message</label>
  <textarea id="text" name="text"></textarea>

  <div class="form-actions">
    <input type="submit" value="Create" />
  </div>
</form>
----

How do we ensure that our form will produce the correct request to create a new message? A naive attempt would look like this:

[source,java]
----
include::{samples-src-test-java}/sample/mockmvc/MockMvcCreateMessageTests.java[tags=create-message-form,indent=0]
----

This test has some obvious problems.
If we updated our controller to use the parameter "message" instead of "text", our test would would incorrectly pass.
To resolve this we could combine our two tests:

[[mock-mvc-test]]
[source,java]
----
include::{samples-src-test-java}/sample/mockmvc/MockMvcCreateMessageTests.java[tags=create-message-form-submit,indent=0]
----

This would reduce the risk of our test incorrectly passing, but there are still some problems:

* What if we had multiple forms on our page? Admittedly we could update our xpath expressions, but they get more complicated the more factors we take into account (are the fields the correct type, are the fields enabled, etc).
* Another issue is that we are doing double the work we would expect.
We must first verify the view and then we submit the view with the same parameters we just verified.
Ideally this could be done all at once.
* Last, there are some things that we still cannot account for.
For example, what if the form has JavaScript validation that we wish to validate too?

The overall problem is that testing a web page is not a single interaction.
Instead, it is a combination of how the user interacts with a web page and how that web page interacts with other resources.
For example, the result of form view is used as an input to a user for creating a message.
Another example is that our form view utilizes additional resources, like JavaScript validation, that impact the behavior of the page.

=== Integration testing to the rescue?

To resolve the issues above we could perform integration testing, but this has some obvious drawbacks.
Consider testing the view that allows us to page through the messages.
We might need the following tests:

* Does our page display a message to the user indicating that no results are available when the messages are empty?
* Does our page properly display a single message?
* Does our page properly support paging?

To set these tests up we would need to ensure our database contained the proper messages in it.
This leads to a number of problems:

* Ensuring the proper messages are in the database can be tedious (think possible foreign keys).
* Testing would be slow since each test would require ensuring the database was in the correct state.
* Since our database needs to be in a specific state, we cannot run the test in parallel.
* Assertions on things like auto generated ids, timestamps, etc can be challenging.

These problems do not mean that we should abandon integration testing all together.
Instead, we can reduce the number of integration tests by moving our detailed tests to use mock services which will perform much faster.
We can then use fewer integration tests that validate simple workflows to ensure that everything works together properly.

=== Enter Spring MVC Test HtmlUnit

So how can we provide a balance between testing the interactions of our pages and still get performance? I'm sure you already guessed it...Spring MVC Test HtmlUnit will allow us to:

* Easily test our pages using tools (i.e. HtmlUnit, WebDriver, & Geb) that we already use for integration testing without starting an application server
* Support testing of JavaScript
* Optionally test using mock services to speed up testing.

== Getting Started

Here is an outline to getting started quickly.

* <<running-the-sample-project>> - Try out working samples!
* Select your method of integration
** <<mockmvc-and-htmlunit>> - Use this option if you want the raw libraries
** <<mockmvc-and-webdriver>> - Use this option to ease development and be able to reuse code between integration and end-to-end testing.
** <<mockmvc-and-geb>> - Use this option if you like using Groovy for testing, would like to ease development, and be able to reuse code between integration and end-to-end testing.
* <<updating-dependencies>>
** <<building-with-maven>>
** <<building-with-gradle>>

== Updating Dependencies

Before you use the project, you must ensure to update your dependencies.
Instructions for building with Maven and Gradle have been provided below:

 * <<building-with-maven>>
 * <<building-with-gradle>>

=== Building with Maven

The project is available in the https://github.com/SpringSource/spring-framework/wiki/SpringSource-repository-FAQ[Spring Maven Repository].
If you are using Maven, you will want to make the following updates.

ifeval::[{snapshot} == true]
When using a snapshot version, you need to ensure you have included the Spring Snapshot repository.

[source,xml]
----
<repository>
  <id>spring-snapshot</id>
  <url>https://repo.spring.io/libs-snapshot</url>
</repository>
----
endif::[]

ifeval::[{milestone} == true]
When using a milestone version, you need to ensure you have included the Spring Milestone repository.

[source,xml]
----
<repository>
  <id>spring-milestone</id>
  <url>https://repo.spring.io/libs-milestone</url>
</repository>
----
endif::[]

ifeval::[{milestone} == true]
Stable releases are included in Maven Central, so generally you do not need to include any additional repositories.
endif::[]

Then ensure you have added the dependencies:

[source,xml]
[subs="verbatim,attributes"]
----
<dependency>
  <groupId>org.springframework.test.htmlunit</groupId>
  <artifactId>spring-test-htmlunit</artifactId>
  <version>{project-version}</version>
  <scope>test</scope>
</dependency>

<!-- necessary only if you are using WebDriver -->
<dependency>
  <groupId>org.seleniumhq.selenium</groupId>
  <artifactId>selenium-htmlunit-driver</artifactId>
  <version>{selenium-version}</version>
  <scope>test</scope>
</dependency>

<!-- necessary only if you are using Geb -->
<dependency>
  <groupId>org.gebish</groupId>
  <artifactId>geb-spock</artifactId>
  <version>{geb-version}</version>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>org.spockframework</groupId>
  <artifactId>spock-spring</artifactId>
  <version>{spock-version}</version>
  <scope>test</scope>
</dependency>
----

=== Building with Gradle

The project is available in the https://github.com/SpringSource/spring-framework/wiki/SpringSource-repository-FAQ[Spring Maven Repository].
If you are using Gradle, you will want to make the following updates.


ifeval::[{snapshot} == true]
If you want to use the latest snapshot, ensure you include the Spring Snapshot repository in your build.gradle:

[source,groovy]
----
repositories {
  maven { url 'https://repo.spring.io/libs-snapshot' }
}
----
endif::[]

ifeval::[{milestone} == true]
If you want the latest milestone, ensure you include the Spring Milestone repository in your build.gradle:

[source,groovy]
----
repositories {
  maven { url 'https://repo.spring.io/libs-milestone' }
}
----
endif::[]


ifeval::[{milestone} == true]
If you want the latest release, ensure you include the Maven Central repository in your build.gradle:

[source,groovy]
----
repositories {
  mavenCentral()
}
----
endif::[]

Then ensure you have added the necessary dependencies:

[source,groovy]
[subs="verbatim,attributes"]
----
dependencies {
  testCompile 'org.springframework.test.htmlunit:spring-test-htmlunit:{project-version}'

  // necessary only if you are using WebDriver
  testCompile "org.seleniumhq.selenium:selenium-htmlunit-driver:{selenium-version}"

  // necessary only if you are using Geb
  testCompile "org.gebish:geb-spock:{geb-version}"
  testCompile "org.spockframework:spock-spring:{spock-version}"
}
----

== MockMvc and HtmlUnit

Now that we have the <<updating-dependencies,correct dependencies>>, we can use HtmlUnit in our unit tests.
Our example assumes you already have JUnit as a dependency.
If you have not added it, please update your classpath accordingly.

NOTE: The complete code sample for using HtmlUnit and Spring MVC Test can be found in https://github.com/spring-projects/spring-test-htmlunit/blob/master/mail-webapp/src/test/java/sample/mockmvc/MockMvcCreateMessageTests.java[MockMvcCreateMessageTests].

=== HtmlUnit JUnit Spring Setup

In order to use HtmlUnit and Spring MVC Test we must first initialize our test.
There is plenty of documentation on how to Spring's Test support, but we will review the basic steps below.

The first step is to create a new JUnit class that is annotated as shown below:

[source,java]
----
include::{samples-src-test-java}/sample/htmlunit/MockMvcHtmlUnitCreateMessageTests.java[tags=junit-spring-setup,indent=0]

    ...
}
----

<1> `@RunWith(SpringJUnit4ClassRunner.class)` allows Spring to perform dependency injection on our `MockMvcHtmlUnitCreateMessageTest`.
This is why our `@Autowired` annotations will be honored.
<2> `@ContextConfiguration` tells Spring what configuration to load.
You will notice that we are loading a mock instance of our data tier to improve the performance of our tests.
If we wanted, we could optionally run the tests against a real database.
However, this has the disadvantages we <<integration-testing-to-the-rescue,mentioned previously>>.
<3> `@WebAppConfiguration` indicates to `SpringJUnit4ClassRunner` that it should create a `WebApplicationContext` rather than a `ApplicationContext`.
<4> `@WithMockUser` runs all the tests as a user name "user" with the role "ROLE_USER" using Spring Security's test support.
Obviously we don't have to leverage the Spring Security support, but it is quite convenient that we do not need to authenticate before each tests allowing for better isolation and performance.

Next we need to create a special instance of `WebClient` that uses `MockMvc` instead of HTTP to make requests.
We can use `MockMvcWebClientBuilder` as a simple way to do this.

[source,java]
----
include::{samples-src-test-java}/sample/htmlunit/MockMvcHtmlUnitCreateMessageTests.java[tags=webclient,indent=0]
----

NOTE: This is a simple example of using `MockMvcWebClientBuilder`.
For more advanced usage, refer to <<Advanced MockMvcWebClientBuilder>>

This will ensure any URL that has a host of "localhost" will be directed at our MockMvc instance without the need for HTTP.
Any other URL will be requested as normal.
This allows for easily testing with the use of CDNs.

=== Using HtmlUnit

Now we can use HtmlUnit as we normally would, but without the need to deploy our application.
For example, we can request the view to create a message with the following:

[source,java]
----
include::{samples-src-test-java}/sample/htmlunit/MockMvcHtmlUnitCreateMessageTests.java[tags=create-form,indent=0]
----

NOTE: The the context path is "".
Alternatively, we could have passed in an optional second argument to `MockMvcWebConnection` to specify an alternative context path.

We can then fill out the form and submit it to create a message.

[source,java]
----
include::{samples-src-test-java}/sample/htmlunit/MockMvcHtmlUnitCreateMessageTests.java[tags=submit-form,indent=0]
----

Finally, we can verify that a new message was created successfully

[source,java]
----
include::{samples-src-test-java}/sample/htmlunit/MockMvcHtmlUnitCreateMessageTests.java[tags=verify-form,indent=0]
----

This improves on our <<mock-mvc-test,MockMvc test>> in a number of ways.
First we no longer have to explicitly verify our form and then create a request that looks like the form.
Instead, we request the form, fill it out, and submit it.
This reduces the overhead significantly.

Another important factor is that http://htmlunit.sourceforge.net/javascript.html[HtmlUnit uses Mozilla Rhino engine] to evaluate JavaScript on your pages.
This means, that we can verify our JavaScript methods as well!

For the complete example, please refer to https://github.com/spring-projects/spring-test-htmlunit/blob/master/mail-webapp/src/test/java/sample/mockmvc/MockMvcCreateMessageTests.java[MockMvcCreateMessageTests].
Refer to the http://htmlunit.sourceforge.net/gettingStarted.html[HtmlUnit documentation] for additional information about using HtmlUnit.


=== Advanced MockMvcWebClientBuilder

In our example above we used `MockMvcWebClientBuilder` in the simplest way possible.

[source,java]
----
include::{samples-src-test-java}/sample/htmlunit/MockMvcHtmlUnitCreateMessageTests.java[tags=webclient,indent=0]
----

We could also perform the exact same setup using the following:

[source,java]
----
include::{docs-src-test-java}/docs/htmlunit/HtmlUnitDocTests.java[tags=webclient-mockmvc,indent=0]
----

By building the `WebClient` with a `MockMvc` instance we have the full power of `MockMvc` at our finger tips.
Ultimately, this is simply performing the following:

TIP: For additional information on creating a `MockMvc` instance refer to the https://docs.spring.io/spring/docs/4.1.x/spring-framework-reference/html/testing.html#spring-mvc-test-framework[Spring MVC Test documentation].

[source,java]
----
include::{docs-src-test-java}/docs/htmlunit/HtmlUnitDocTests.java[tags=webclient-verbose,indent=0]
----

== MockMvc and WebDriver

In the previous section, we have already seen how to use MockMvc with HtmlUnit.
In this section, we will leverage additional abstractions within https://docs.seleniumhq.org/projects/webdriver/[WebDriver] to make things even easier.

NOTE: The complete code sample for using HtmlUnit and Spring MVC Test can be found in https://github.com/spring-projects/spring-test-htmlunit/blob/master/mail-webapp/src/test/java/sample/webdriver/MockMvcHtmlUnitDriverCreateMessageTests.java[MockMvcHtmlUnitDriverCreateMessageTests.java].

[[webdriver-why]]
=== Why WebDriver and MockMvc?

We can already use HtmlUnit and MockMvc, so why would we want to use WebDriver? WebDriver provides a very elegant API and allows us to easily organize our code.
To better understand, let's explore an example.

NOTE: Despite being a part of https://docs.seleniumhq.org/[Selenium], WebDriver does not require a Selenium Server to run your tests.

Suppose we need to ensure that a message is created properly.
The tests involve finding the html inputs, filling them out, and making various assertions.

There are many tests because we want to test error conditions as well.
For example, we want to ensure that if we fill out only part of the form we get an error.
If we fill out the entire form, the newly created message is displayed afterwards.

If one of the fields was named "summary", then we might have something like the following repeated everywhere within our tests:

[source,java]
----
include::{docs-src-test-java}/docs/webdriver/why/WhyWebDriversTests.java[tags=set-summary-input,indent=0]
----

So what happens if we change the id to be "smmry".
This means we would have to update all of our tests! Instead we would hope that we wrote a bit more elegant code where filling out the form was in its own method:

[source,java]
----
include::{docs-src-test-java}/docs/webdriver/why/WhyWebDriversTests.java[tags=create-message,indent=0]
    ...
}

include::{docs-src-test-java}/docs/webdriver/why/WhyWebDriversTests.java[tags=set-summary,indent=0]
----

This ensures that if we change the UI we do not have to update all of our tests.

We might take it a step further and place this logic within an Object that represents the `HtmlPage` we are currently on.

[source,java]
----
include::{docs-src-test-java}/docs/webdriver/why/CreateMessagePage.java[tags=class]
----

Formerly, this pattern is known as the https://code.google.com/p/selenium/wiki/PageObjects[Page Object Pattern].
While we can certainly do this with HtmlUnit, WebDriver provides some tools that we will explore in the following sections make this pattern much easier.

=== WebDriver JUnit Spring Setup

In order to use WebDriver and Spring MVC Test we must first initialize our test.
There is plenty of documentation on how to Spring's Test support, but we will review the basic steps below.

The first step is to create a new JUnit class that is annotated as shown below:

[source,java]
----
include::{samples-src-test-java}/sample/webdriver/MockMvcHtmlUnitDriverCreateMessageTests.java[tags=junit-spring-setup,indent=0]

    ...
}
----

<1> `@RunWith(SpringJUnit4ClassRunner.class)` allows Spring to perform dependency injection on our `MockMvcHtmlUnitCreateMessageTest`.
This is why our `@Autowired` annotations will be honored.
<2> `@ContextConfiguration` tells Spring what configuration to load.
You will notice that we are loading a mock instance of our data tier to improve the performance of our tests.
If we wanted, we could optionally run the tests against a real database.
However, this has the disadvantages we <<integration-testing-to-the-rescue,mentioned previously>>.
<3> `@WebAppConfiguration` indicates to `SpringJUnit4ClassRunner` that it should create a `WebApplicationContext` rather than a `ApplicationContext`.
<4> `@WithMockUser` runs all the tests as a user name "user" with the role "ROLE_USER" using Spring Security's test support.
Obviously we don't have to leverage the Spring Security support, but it is quite convenient that we do not need to authenticate before each tests allowing for better isolation and performance.

Next we need to create a special instance of `WebDriver` that uses `MockMvc` instead of HTTP to make requests.
We can use `MockMvcHtmlUnitDriverBuilder` as a simple way to do this.

[source,java]
----
include::{samples-src-test-java}/sample/webdriver/MockMvcHtmlUnitDriverCreateMessageTests.java[tags=webdriver,indent=0]
----

NOTE: This is a simple example of using `MockMvcHtmlUnitDriverBuilder`.
For more advanced usage, refer to <<Advanced MockMvcHtmlUnitDriverBuilder>>

This will ensure any URL that has a host of "localhost" will be directed at our MockMvc instance without the need for HTTP.
Any other URL will be requested as normal.
This allows for easily testing with the use of CDNs.

=== Using WebDriver

Now we can use WebDriver as we normally would, but without the need to deploy our application.
For example, we can request the view to create a message with the following:

[source,java]
----
include::{samples-src-test-java}/sample/webdriver/MockMvcHtmlUnitDriverCreateMessageTests.java[tags=to-create-message,indent=0]
----

We can then fill out the form and submit it to create a message.

[source,java]
----
include::{samples-src-test-java}/sample/webdriver/MockMvcHtmlUnitDriverCreateMessageTests.java[tags=create-message,indent=0]
----

This improves on the design of our https://spring.io/blog/2014/03/21/spring-mvc-test-with-htmlunit[HtmlUnit test] by leveraging the Page Object Pattern.
As we mentioned in <<webdriver-why>>, we could use the Page Object Pattern with HtmlUnit, but it is much easier now.
Let's take a look at our `CreateMessagePage`.

[source,java]
----
include::{samples-src-test-java}/sample/webdriver/pages/CreateMessagePage.java[tags=class,indent=0]
----

<1> The first thing you will notice is that our `CreateMessagePage` extends the `AbstractPage`.
We won't go over the details of `AbstractPage`, but in summary it contains all the common functionality of all our pages.
For example, if your application has a navigational bar, global error messages, etc.
This logic can be placed in a shared location.

<2> The next thing you will find is that we have a member variable for each of the parts of the HTML, `WebElement`, we are interested in.
``WebDriver``'s https://code.google.com/p/selenium/wiki/PageFactory[PageFactory] allows us to remove a lot of code from HtmlUnit version of `CreateMessagePage` by automatically resolving each `WebElement`.
The https://selenium.googlecode.com/git/docs/api/java/org/openqa/selenium/support/PageFactory.html#initElements-org.openqa.selenium.WebDriver-java.lang.Class-[PageFactory#initElements(WebDriver,Class<T>)] method will automatically resolve each `WebElement` by using the field name and trying to look it up by id or name of the element on the HTML page.
<3> We can use the https://code.google.com/p/selenium/wiki/PageFactory#Making_the_Example_Work_Using_Annotations[@FindBy annotation] to override the default.
Our example demonstrates how we can use the `@FindBy` annotation to lookup our submit button using the css selector of *input[type=submit]*.

Finally, we can verify that a new message was created successfully

[source,java]
----
include::{samples-src-test-java}/sample/webdriver/MockMvcHtmlUnitDriverCreateMessageTests.java[tags=create-message-assert,indent=0]
----

We can see that our `ViewMessagePage` can allow us to interact with our custom domain model.
For example, it exposes a method that returns a `Message` object.

[source,java]
----
include::{samples-src-test-java}/sample/webdriver/pages/ViewMessagePage.java[tags=get-message,indent=0]
----

We can then leverage the rich domain objects in our assertions.
We do this by creating a https://github.com/alexruiz/fest-assert-2.x/wiki/Creating-specific-assertions[custom fest assertion] that allows us to verify all the properties of the actual `Message` are equal to the expected `Message`.
You can view the details of the custom assertion in https://github.com/spring-projects/spring-test-htmlunit/blob/master/mail-webapp/src/test/java/sample/fest/Assertions.java[Assertions] and https://github.com/spring-projects/spring-test-htmlunit/blob/master/mail-webapp/src/test/java/sample/fest/MessageAssert.java[MessageAssert]

Last, don't forget to close the `WebDriver` instance when we are done.

[source,java]
----
include::{samples-src-test-java}/sample/webdriver/MockMvcHtmlUnitDriverCreateMessageTests.java[tags=cleanup,indent=0]
----

For additional information on using WebDriver, refer to the https://code.google.com/p/selenium/wiki/GettingStarted[WebDriver documentation].

=== Advanced MockMvcHtmlUnitDriverBuilder

In our example above we used `MockMvcHtmlUnitDriverBuilder` in the simplest way possible.

[source,java]
----
include::{samples-src-test-java}/sample/webdriver/MockMvcHtmlUnitDriverCreateMessageTests.java[tags=webdriver,indent=0]
----

We could also perform the exact same setup using the following:

[source,java]
----
include::{docs-src-test-java}/docs/webdriver/WebDriverDocTests.java[tags=webdriver-mockmvc,indent=0]
----

By building the `WebDriver` with a `MockMvc` instance we have the full power of `MockMvc` at our finger tips.
Ultimately, this is simply performing the following:

TIP: For additional information on creating a `MockMvc` instance refer to the https://docs.spring.io/spring/docs/4.1.x/spring-framework-reference/html/testing.html#spring-mvc-test-framework[Spring MVC Test documentation].

[source,java]
----
include::{docs-src-test-java}/docs/webdriver/WebDriverDocTests.java[tags=webdriver-verbose,indent=0]
----

== MockMvc and Geb

In the previous section, we saw how to use MockMvc with WebDriver.
In this section, we will use http://www.gebish.org/[Geb] to make our tests more Groovy.

[[geb-why]]
=== Why Geb and MockMvc?

Geb is backed by WebDriver, so it offers many of the <<webdriver-why,same benefits>> we got from WebDriver.
However, Geb makes things even easier by taking care of some of the boiler plate code for us.
Of course we want to use MockMvc so that we do no need to deploy our code to a server.
The easiest way to understand the benefits of using Geb is to jump into an example.

NOTE: Another great feature of Geb is its http://www.gebish.org/manual/current/[exceptional documentation].

=== WebDriver Geb and Spring Setup

Once we have the <<updating-dependencies,correct dependencies>>, we can use Geb in our unit tests.

NOTE: The complete code sample for using Geb and Spring MVC Test can be found in https://github.com/spring-projects/spring-test-htmlunit/blob/master/mail-webapp/src/test/groovy/sample/geb/GebCreateMessagesSpec.groovy[GebCreateMessagesSpec].

In order to use HtmlUnit and Spring MVC Test we must first create a `MockMvc` instance.
There is plenty of documentation on how to create a `MockMvc` instance, but we will review how to create a `MockMvc` instance very quickly in this section.

The first step is to create a new `GebReportingSpec` class that is annotated as shown below:

[source,groovy]
----
include::{samples-src-test-groovy}/sample/geb/GebCreateMessagesSpec.groovy[tags=spock-spring-setup,indent=0]

    ...
}
----

NOTE: For this to work ensure to add the spock-spring dependency as illustrated in the <<updating-dependencies>> section.
This is why `@Autowired` annotations will be honored.

<1> `@ContextConfiguration` tells Spring what configuration to load.
You will notice that we are loading a mock instance of our data tier to improve the performance of our tests.
If we wanted, we could optionally run the tests against a real database.
However, this has the disadvantages we <<integration-testing-to-the-rescue,mentioned previously>>.
<2> `@WebAppConfiguration` indicates that a `WebApplicationContext` should be created rather than a `ApplicationContext`.
<3> `@WithMockUser` runs all the tests as a user name "user" with the role "ROLE_USER" using Spring Security’s test support.
Obviously we don’t have to leverage the Spring Security support, but it is quite convenient that we do not need to authenticate before each tests allowing for better isolation and performance.
<4> We extend `GebReportingSpec` to provide http://www.gebish.org/manual/current/testing.html#spock_junit__testng[Geb integration] for Geb's http://www.gebish.org/manual/current/testing.html#reporting[reporting functionality].

Next we need to create a special instance of `WebDriver` that uses `MockMvc` instead of HTTP to make requests.
We can use `MockMvcHtmlUnitDriverBuilder` as a simple way to use Geb's http://www.gebish.org/manual/current/all.html#explicit_driver_management[Explicit Driver Management] facility.

[source,groovy]
----
include::{samples-src-test-groovy}/sample/geb/GebCreateMessagesSpec.groovy[tags=webdriver,indent=0]
----

NOTE: This is a simple example of using `MockMvcHtmlUnitDriverBuilder`.
For more advanced usage, refer to <<Advanced MockMvcHtmlUnitDriverBuilder>>

This will ensure any URL that has a host of "localhost" will be directed at our MockMvc instance without the need for HTTP.
Any other URL will be requested as normal.
This allows for easily testing with the use of CDNs.

=== Using Geb

Now we can use Geb as we normally would, but without the need to deploy our application.
For example, we can request the view to create a message with the following:

[source,groovy]
----
include::{samples-src-test-groovy}/sample/geb/GebCreateMessagesSpec.groovy[tags=to-create-message,indent=0]
----

We can then fill out the form and submit it to create a message.

[source,groovy]
----
include::{samples-src-test-groovy}/sample/geb/GebCreateMessagesSpec.groovy[tags=create-message,indent=0]
----

Any unrecognized method calls or property accesses/references that are not found will be forwarded to the current page object.
This removes a lot of the boilerplate code we needed when using WebDriver directly.

Additionally, this improves on the design of our https://spring.io/blog/2014/03/21/spring-mvc-test-with-htmlunit[HtmlUnit test].
The most obvious change is that we are now using the Page Object Pattern.
As we mentioned in <<webdriver-why>>, we could use the Page Object Pattern with HtmlUnit, but it is much easier now.

Let's take a look at our `CreateMessagePage`.

[source,groovy]
----
include::{samples-src-test-groovy}/sample/geb/pages/CreateMessagePage.groovy[tags=class,indent=0]
----

The first thing you will notice is that our `CreateMessagePage` extends the `Page`.
We won't go over the details of `Page`, but in summary it contains base functionality for all our pages.

The next thing you will notice is that we define a URL in which this page can be found.
This allows us to navigate to the page with:

[source,groovy]
----
include::{samples-src-test-groovy}/sample/geb/GebCreateMessagesSpec.groovy[tags=to-create-message,indent=0]
----

We also have a closure that determines if we are at the specified page.
It should return true if we are on the correct page.
This is why we can assert that we are on the correct page with:

[source,groovy]
----
include::{samples-src-test-groovy}/sample/geb/GebCreateMessagesSpec.groovy[tags=at-create-message,indent=0]
----

NOTE: We use an assertion in the closure, so we can determine where things went wrong if we were at the wrong page.

We last create a content closure that specifies all the areas of interest within the page.
We can use a http://www.gebish.org/manual/current/intro.html#the_jquery_ish_navigator_api[jQuery-ish Navigator API] to select the content we are interested in.

Finally, we can verify that a new message was created successfully

[source,groovy]
----
include::{samples-src-test-groovy}/sample/geb/GebCreateMessagesSpec.groovy[tags=create-message-assert,indent=0]
----

== Running the sample project

The following provides information on setting up a development environment that can run https://github.com/spring-projects/spring-test-htmlunit/tree/master/mail-webapp[the sample] in https://www.springsource.org/sts[Spring Tool Suite 3.6.4+].
Other IDE's should work using Gradle's IDE support, but have not been tested.

* IDE Setup
** Install Spring Tool Suite 3.6.4+
** You will need the following plugins installed (can be found on the Extensions Page)
** Gradle Eclipse
** Groovy Eclipse plugin
** Groovy 2.2 compiler should be enabled in Window->Preferences Groovy->Compiler
* Importing the project into Spring Tool Suite
** File->Import...->Gradle Project

Any tests ending in ITest or ISpec require the application to be deployed to http://localhost:9990/.
You should be able to do this easily using Eclipse WTP.
Other tests run using Sprint Test MVC and do not require the application to be deployed.

== Minimum Requirements

MockMvc will work with templating technologies that do not rely on a Servlet Container (i.e. Thymeleaf, Freemarker, Velocity, etc).
It does not work with JSPs since they rely on the Servlet Container.

=== Minimum JDK

The miniumum JDK is 1.7 in order to work with HtmlUnit and Selenium which also work with JDK 1.7.

=== Minimum Spring Version

The project should work with Spring 3.2.0+, but use with Spring 4.0 is encouraged.

== Contributing

Before contributing or logging an issue please be sure to the issue does not already exist in this project's https://github.com/spring-projects/spring-test-htmlunit/issues[issue tracking].
If one does not exist, please create an issue.

If you see anything you'd like to change we encourage taking advantage of github's social coding features by making the change in a https://help.github.com/forking/[fork of this repository] and sending a pull request.

Before we accept a non-trivial patch or pull request we will need you to sign the https://support.springsource.com/spring_committer_signup[contributor's agreement].
Signing the contributor's agreement does not grant anyone commit rights to the main repository, but it does mean that we can accept your contributions, and you will get an author credit if we do.
Active contributors might be asked to join the core team, and given the ability to merge pull requests.

== License

The Spring MVC Test HtmlUnit project is available under version 2.0 of the http://www.apache.org/licenses/LICENSE-2.0[Apache License].

== Appendix

=== Migrating from 1.0.0.M2 to 1.0.0.RC1

Below is a summary of how to migrate between spring-test-htmlunit-1.0.0.M2 and spring-test-htmlunit-1.0.0.RC1.
For a complete list of changes refer to the https://github.com/spring-projects/spring-test-htmlunit/issues?utf8=%E2%9C%93&q=is%3Aissue+milestone%3A1.0.0.RC1+[changelog].

==== New Maven Coordinates

We have changed the Group ID for the project.
Refer to <<Updating Dependencies>> for details.

==== MockMvc WebClient & WebDriver Builders

This release adds builders for MockMvc and HtmlUnit integration.
The builders provide a number of benefits:

* Simplify the setup
* Allow for more configuration options
* By default any URL that has localhost is processed by MockMvc
(i.e. http://localhost/something) while any other host is retrieved
normally (i.e. https://cdn.example.com/jquery.js).

===== Migrating to HtmlUnit Builders

In the previous release HtmlUnit was initialized with the following
code:

[source,java]
----
MockMvc mockMvc = MockMvcBuilders
    .webAppContextSetup(context)
    .apply(springSecurity())
    .build();
webClient = new WebClient();
webClient.setWebConnection(new MockMvcWebConnection(mockMvc));
----

While this method is still supported, you can simplify your setup using:

[source, java]
----
webClient = MockMvcWebClientBuilder
    .webAppContextSetup(context, springSecurity())
    // contextPath defaults to ""
    // previous releases use to be treated as null
    .contextPath(null)
    .createWebClient();
----

For additional details about `MockMvcWebClientBuilder` see <<Advanced MockMvcWebClientBuilder>>.

===== Migrating to WebDriver Builders

In the previous release WebDriver was initialized with the following code:

[source,java]
-----
MockMvc mockMvc = MockMvcBuilders
    .webAppContextSetup(context)
    .apply(springSecurity())
    .build();
webDriver = new MockMvcHtmlUnitDriver(mockMvc, true);
-----

`MockMvcHtmlUnitDriver` was removed due to the fact that it was too complex and did not allow for more advanced configurations (i.e. context path).

Now we can configure our webDriver using the following:

[source,java]
----
webDriver = MockMvcHtmlUnitDriverBuilder
    .webAppContextSetup(context, springSecurity())
    // contextPath defaults to ""
    // previous releases use to be treated as null
    .contextPath(null)
    .createDriver();
----

For additional details about `MockMvcHtmlUnitDriverBuilder` see <<Advanced MockMvcHtmlUnitDriverBuilder>>.

===== Migrating to Geb Builders

Geb use to be initialized with the following:

[source,groovy]
----
MockMvc mockMvc = MockMvcBuilders.webAppContextSetup(context).build()
browser.driver = new MockMvcHtmlUnitDriver(mockMvc, true)
----

`MockMvcHtmlUnitDriver` was removed due to the fact that it was too complex and did not allow for more advanced configurations (i.e. context path).

Now we can configure Geb using the following:

[source,groovy]
----
browser.driver = MockMvcHtmlUnitDriverBuilder
    .webAppContextSetup(context, springSecurity())
    .createDriver()
----


==== Default Context Path is now ""

Based upon community feedback, the default context path is now "".
This means if you are using a previous release, you will need to update the URL that is configured.
For example:

===== Migrating Context Path for HtmlUnit

[source,java]
----
HtmlPage createMsgFormPage =  webClient.getPage("http://localhost/context-root/messages/form");

// changes to...

include::{samples-src-test-java}/sample/htmlunit/MockMvcHtmlUnitCreateMessageTests.java[tags=create-form,indent=0]
----

===== Migrating Context Path for WebDriver

[source,java]
----
webDriver.get("http://localhost:9990/mail/messages/form");

// changes to...

webDriver.get("http://localhost:9990/messages/form");
----

===== Migrating Context Path for Geb

[source,groovy]
----
baseUrl = 'http://localhost:8080/mail/'

// changes to...

baseUrl = 'http://localhost:8080/'
----
